package com.over.internal;

public class Runner {
    public static void main(String[] args) {
        Biscuit biscuit = new Biscuit(200, "ajhk", "parleg");
        System.out.println(biscuit);
        Spoon spoon = new Spoon(900,"valcano","casio");
        System.out.println(spoon);
        Chair chair = new Chair("camel",100,"plastic");
        System.out.println(chair);
        Table table = new Table(100,"new","bigone");
        System.out.println(table);
        Fan fan = new Fan(90,180,"small fan");
        System.out.println(fan);
        Bottle bottle = new Bottle("2003","white","castral");
        System.out.println(bottle);
        Pen pen = new Pen("id192","small","wood");
        System.out.println(pen);
        Pencil pencil = new Pencil("apsara","large","erasable");
        System.out.println(pencil);
        Book book = new Book("longbook","camel","classmate");
        System.out.println(book);
        Laptop laptop = new Laptop("steel","hp","hp pavillion");
        System.out.println(laptop);
        Mobile mobile = new Mobile("large","white",800);
        System.out.println(mobile);
        Mouse mouse = new Mouse("hp","2003","70cm");
        System.out.println(mouse);
        Keyboard keyboard = new Keyboard("steel","2021","Large");
        System.out.println(keyboard);
        Window window = new Window("front","wood","recent");
        System.out.println(window);
        Door door = new Door(90,"wood","asian");
        System.out.println(door);
        Lamp lamp = new Lamp("glass","bulb",50);
        System.out.println(lamp);
        Bag bag = new Bag("large","adidas",20);
        System.out.println(bag);
        Phone phone = new Phone(90000,"steel and iron","redmi");
        System.out.println(phone);
        Television television = new Television("Old tv",1,"12 inch");
        System.out.println(television);
        Cup cup = new Cup(90,"big","droom");
        System.out.println(cup);
        Plate plate = new Plate(908,"stainless steel","browm");
        System.out.println(plate);
        Brush brush = new Brush("black",8,100);
        System.out.println(brush);
        Comb comb = new Comb(2,"ajantha","new model");
        System.out.println(comb);
        Ruler ruler = new Ruler("king",90,70);
        System.out.println(ruler);
//        Carpet carpet = new Carpet();
//        System.out.println(carpet);
//        Notebook notebook = new Notebook();
//        System.out.println(notebook);
//        Printer printer = new Printer();
//        System.out.println(printer);
//        Speaker speaker = new Speaker();
//        System.out.println(speaker);
//        Camera camera = new Camera();
//        System.out.println(camera);
//        Monitor monitor = new Monitor();
//        System.out.println(monitor);
//        Shoe shoe = new Shoe();
//        System.out.println(shoe);
//        Socks socks = new Socks();
//        System.out.println(socks);
//        Hat hat = new Hat();
//        System.out.println(hat);
//        Jacket jacket = new Jacket();
//        System.out.println(jacket);
//        Shirt shirt = new Shirt();
//        System.out.println(shirt);
//        Pants pants = new Pants();
//        System.out.println(pants);
//        Glove glove = new Glove();
//        System.out.println(glove);
//        Watch watch = new Watch();
//        System.out.println(watch);
//        Clock clock = new Clock();
//        System.out.println(clock);
//        Projector projector = new Projector();
//        System.out.println(projector);
//        Drone drone = new Drone();
//        System.out.println(drone);
//        Cushion cushion = new Cushion();
//        System.out.println(cushion);
//        Mat mat = new Mat();
//        System.out.println(mat);
//        Mirror mirror = new Mirror();
//        System.out.println(mirror);
//        Frame frame = new Frame();
//        System.out.println(frame);
//        Mug mug = new Mug();
//        System.out.println(mug);
//        Stick stick = new Stick();
//        System.out.println(stick);
//        Vase vase = new Vase();
//        System.out.println(vase);
//        Knife knife = new Knife();
//        System.out.println(knife);
//        Fork fork = new Fork();
//        System.out.println(fork);
//        Towel towel = new Towel();
//        System.out.println(towel);
//        Sponge sponge = new Sponge();
//        System.out.println(sponge);
//        Bucket bucket = new Bucket();
//        System.out.println(bucket);
//        Mop mop = new Mop();
//        System.out.println(mop);
//        Broom broom = new Broom();
//        System.out.println(broom);
//        Curtain curtain = new Curtain();
//        System.out.println(curtain);
//        Tissue tissue = new Tissue();
//        System.out.println(tissue);
//        Pan pan = new Pan();
//        System.out.println(pan);
//        Pot pot = new Pot();
//        System.out.println(pot);
//        Kettle kettle = new Kettle();
//        System.out.println(kettle);
//        Helmet helmet1 = new Helmet();
//        System.out.println(helmet1);
//        Basket basket = new Basket();
//        System.out.println(basket);
//        Rope rope = new Rope();
//        System.out.println(rope);
//        Chain chain = new Chain();
//        System.out.println(chain);
//        Ball ball = new Ball();
//        System.out.println(ball);
//        Bat bat = new Bat();
//        System.out.println(bat);
//        Helmet helmet2 = new Helmet();
//        System.out.println(helmet2);
//        Ring ring = new Ring();
//        System.out.println(ring);
//        Necklace necklace = new Necklace();
//        System.out.println(necklace);
//        Earring earring = new Earring();
//        System.out.println(earring);
//        Bracelet bracelet = new Bracelet();
//        System.out.println(bracelet);
//        Toy toy = new Toy();
//        System.out.println(toy);
//        Board board = new Board();
//        System.out.println(board);
//        Glasses glasses = new Glasses();
//        System.out.println(glasses);
//        Pad pad = new Pad();
//        System.out.println(pad);
//        Joystick joystick = new Joystick();
//        System.out.println(joystick);
//        Bulb bulb = new Bulb();
//        System.out.println(bulb);
//        Plug plug = new Plug();
//        System.out.println(plug);
//        Socket socket = new Socket();
//        System.out.println(socket);
//        Adapter adapter = new Adapter();
//        System.out.println(adapter);
//        Cable cable = new Cable();
//        System.out.println(cable);
//        Charger charger = new Charger();
//        System.out.println(charger);
//        Scissor scissor = new Scissor();
//        System.out.println(scissor);
//        Tape tape = new Tape();
//        System.out.println(tape);
//        Envelope envelope = new Envelope();
//        System.out.println(envelope);
//        File file = new File();
//        System.out.println(file);
//        Folder folder = new Folder();
//        System.out.println(folder);
//        Document document = new Document();
//        System.out.println(document);
//        Stapler stapler = new Stapler();
//        System.out.println(stapler);
//        Clip clip = new Clip();
//        System.out.println(clip);
//        Brush brush2 = new Brush();
//        System.out.println(brush2);
//        Palette palette = new Palette();
//        System.out.println(palette);
//        Canvas canvas = new Canvas();
//        System.out.println(canvas);
//        Crayon crayon = new Crayon();
//        System.out.println(crayon);
//        Eraser eraser = new Eraser();
//        System.out.println(eraser);
//        Sharpener sharpener = new Sharpener();
//        System.out.println(sharpener);
//        Scanner scanner = new Scanner();
//        System.out.println(scanner);
//        Tripod tripod = new Tripod();
//        System.out.println(tripod);
//        FanRemote fanremote = new FanRemote();
//        System.out.println(fanremote);
//        Heater heater = new Heater();
//        System.out.println(heater);
    }
}